name: memoapp
services:
  app:
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - WORK_DIR=${WORK_DIR}
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV}
    container_name: memoapp
    # to avoid "PID 1" problem
    init: true
    tty: true
    volumes:
      - ./src:/${WORK_DIR}:delegated
      - ${WORK_DIR}/node_modules
      - ${WORK_DIR}/.yarn
      - ${WORK_DIR}/.cache
    ports:
      - ${PORT_RANGE}:${PORT_RANGE}
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
      - NODE_ENV=${NODE_ENV}
