name: memoapp
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: release
    container_name: memoapp
    ports:
      - "19001:9001"
      - "19002:9002"
      - "19006:9006"
    # to avoid "PID 1" problem
    init: true
    volumes:
      - "./src:/app"
    tty: true
    # command: npm run start:de/usr/src/appv
