name: memoapp
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: release
    container_name: memoapp
    # to avoid "PID 1" problem
    init: true
    volumes:
      - "./src:/app"
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - 19000-19002:19000-19002
    tty: true
